services:
  - type: web
    name: run-lulu-run
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    autoDeploy: true
